services:
    ppa.event_dispatcher:
        class: PPA\core\EventDispatcher
    ppa.entity_manager:
        class: PPA\orm\EntityManager
        arguments:
            - "@ppa.transaction_manager"
            - "@ppa.event_dispatcher"
    ppa.transaction_manager:
        class: PPA\dbal\TransactionManager
        arguments:
            - "@ppa.connection"
            - "@ppa.event_dispatcher"
    ppa.connection:
        class: PPA\dbal\Connection
        factory: ['PPA\dbal\DriverManager', getConnection]
        arguments:
            - "@ppa.event_dispatcher"